# Generated by Django 6.0.7 on 2026-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desination', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_u', models.IntegerField(blank=True, null=True)),
                ('entre', models.IntegerField(blank=True, null=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('total_stock', models.IntegerField(blank=True, null=True)),
                ('sortie', models.IntegerField(blank=True, null=True)),
                ('recette', models.IntegerField(blank=True, null=True)),
                ('montant_physique', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
    ]
