# Generated by Django 6.0.7 on 2026-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effmapp', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
    ]
