# Generated by Django 6.0.7 on 2026-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effmapp', '0003_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='CampagneKurban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='CampagneRamadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='DistributionKurban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='DistributionRamadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Forage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
        migrations.CreateModel(
            name='Volontaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materiel',
            },
        ),
    ]
