# Generated by Django 6.0.7 on 2026-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effmapp', '0004_actualite_beneficiaire_bourse_campagnekurban_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualite',
            options={'verbose_name': 'Actualite'},
        ),
        migrations.AlterModelOptions(
            name='beneficiaire',
            options={'verbose_name': 'Beneficiere'},
        ),
        migrations.AlterModelOptions(
            name='bourse',
            options={'verbose_name': 'Bourse'},
        ),
        migrations.AlterModelOptions(
            name='campagnekurban',
            options={'verbose_name': 'Campagne Kurban'},
        ),
        migrations.AlterModelOptions(
            name='campagneramadan',
            options={'verbose_name': 'Campagne Ramadan'},
        ),
        migrations.AlterModelOptions(
            name='distributionkurban',
            options={'verbose_name': 'Distribution Kurban'},
        ),
        migrations.AlterModelOptions(
            name='distributionramadan',
            options={'verbose_name': 'Distribution Ramadan'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document'},
        ),
        migrations.AlterModelOptions(
            name='don',
            options={'verbose_name': 'Don'},
        ),
        migrations.AlterModelOptions(
            name='donateur',
            options={'verbose_name': 'Donateur'},
        ),
        migrations.AlterModelOptions(
            name='forage',
            options={'verbose_name': 'Forage'},
        ),
        migrations.AlterModelOptions(
            name='galerie',
            options={'verbose_name': 'Galerie'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'verbose_name': 'Projet'},
        ),
        migrations.AlterModelOptions(
            name='volontaire',
            options={'verbose_name': 'Volontaire'},
        ),
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dtn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(default='Madagascar', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
