# Generated by Django 6.0.7 on 2026-07-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effmapp', '0005_alter_actualite_options_alter_beneficiaire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commune',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'District',
            },
        ),
        migrations.CreateModel(
            name='Fokotany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fokotany',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Region',
            },
        ),
        migrations.AlterModelOptions(
            name='beneficiaire',
            options={'verbose_name': 'Beneficiaire'},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'verbose_name': 'Partenaire'},
        ),
        migrations.RenameField(
            model_name='actualite',
            old_name='designation',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='designation',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='quantite',
            new_name='cin',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='date_ajout',
            new_name='dtn',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='etat',
            new_name='sexe',
        ),
        migrations.RenameField(
            model_name='bourse',
            old_name='date_ajout',
            new_name='debut',
        ),
        migrations.RenameField(
            model_name='bourse',
            old_name='designation',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='campagnekurban',
            old_name='date_ajout',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='campagnekurban',
            old_name='quantite',
            new_name='annee',
        ),
        migrations.RenameField(
            model_name='campagnekurban',
            old_name='designation',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='campagneramadan',
            old_name='quantite',
            new_name='annee',
        ),
        migrations.RenameField(
            model_name='campagneramadan',
            old_name='date_ajout',
            new_name='debut',
        ),
        migrations.RenameField(
            model_name='campagneramadan',
            old_name='designation',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='distributionkurban',
            old_name='designation',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='distributionkurban',
            old_name='date_ajout',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='distributionkurban',
            old_name='quantite',
            new_name='nbr_colis',
        ),
        migrations.RenameField(
            model_name='distributionramadan',
            old_name='designation',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='distributionramadan',
            old_name='date_ajout',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='distributionramadan',
            old_name='quantite',
            new_name='nbr_colis',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='designation',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='don',
            old_name='date_ajout',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='don',
            old_name='quantite',
            new_name='montant',
        ),
        migrations.RenameField(
            model_name='don',
            old_name='designation',
            new_name='obsevation',
        ),
        migrations.RenameField(
            model_name='donateur',
            old_name='designation',
            new_name='Pays',
        ),
        migrations.RenameField(
            model_name='donateur',
            old_name='quantite',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='forage',
            old_name='quantite',
            new_name='cout',
        ),
        migrations.RenameField(
            model_name='forage',
            old_name='date_ajout',
            new_name='date_real',
        ),
        migrations.RenameField(
            model_name='forage',
            old_name='designation',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='galerie',
            old_name='designation',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='materiel',
            old_name='designation',
            new_name='categorire',
        ),
        migrations.RenameField(
            model_name='materiel',
            old_name='date_ajout',
            new_name='date_achat',
        ),
        migrations.RenameField(
            model_name='materiel',
            old_name='quantite',
            new_name='sn',
        ),
        migrations.RenameField(
            model_name='partenaire',
            old_name='designation',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='partenaire',
            old_name='quantite',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='quantite',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='designation',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='date_ajout',
            new_name='date_f',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='bourse',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='bourse',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='campagnekurban',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='campagneramadan',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='distributionkurban',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='distributionramadan',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='document',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='document',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='don',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='donateur',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='donateur',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='forage',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='galerie',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='galerie',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='galerie',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='volontaire',
            name='date_ajout',
        ),
        migrations.AddField(
            model_name='actualite',
            name='auteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='contenu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='resume',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='handicap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nbr_enfant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='obsevation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='s_famille',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='ecole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='etudiant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='parrain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bourse',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campagnekurban',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagnekurban',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagnekurban',
            name='fin',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagnekurban',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campagnekurban',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campagneramadan',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagneramadan',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagneramadan',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagneramadan',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campagneramadan',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distributionkurban',
            name='observation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionkurban',
            name='poid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionramadan',
            name='observation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionramadan',
            name='poid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='auteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='don',
            name='devise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='organisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='site_web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='lien_maps',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='profondeur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galerie',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galerie',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='observation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='valeur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='convention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='date_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='date_i',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_moyen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_i',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='donateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
